### ISSUE TITLE
Flickering of pages when swipe or fling up or down 

### ISSUE THREAD

**Issue by therealjohnsummer** [espresso3389/flutter_pdf_render#85] opened 2022-07-24 13:03 UTC
Hi - I am noticing a FLICKER when I scroll up or down (Shows more on swipe/fling down) - it appears as if a page that is previously shown quickly flashes before the new page is rendered.

Happens on both live device and simulator.

So far have tested this on iOS (Live device) using latest version of this plugin.

**Comment by razfazz** [comment] 2022-07-28 11:08
i have the same issue

**Comment by therealjohnsummer** [comment] 2022-07-28 19:51
@razfazz - To overcome the issue I now just render the PDF pages and wrap in a List without pinch support. Then apply a simple Gesture to trap pinches and apply the zoom myself making use of InteractiveViewer.

**Comment by espresso3389** [comment] 2022-07-29 09:25
Duplicate #84

**Comment by therealjohnsummer** [comment] 2022-07-30 13:58
Hi Takashi - I can confirm this also happens on Android Devices also.

The issue is only when you use the  **PdfViewer** and doesnt happen if you use a **PdfDocumentLoader** but with the latter, since there is no controller we cannot navigate to a specific page and also loose Pinch/Zoom support.

If you need help testing on Live devices for iOS/Android I'd be happy to help.

**Comment by espresso3389** [comment] 2022-07-30 14:06
@therealjohnsummer 
Could you please check #84 to determine whether your issue is identical to #84 or not?
#84 has a movie that explains the flicker casued on Flutter Web.

**Comment by therealjohnsummer** [comment] 2022-07-30 14:45
@espresso3389 Yes, it looks very similar - please see screencast : 

https://user-images.githubusercontent.com/54981654/181919501-29779a9f-ce71-40be-afbe-f7be02ef8535.mp4

**Comment by espresso3389** [comment] 2022-07-30 14:51
@therealjohnsummer 
Oh, it seems the identical issue... OK, anyway, I'm working on #84 now. And after finishing #84, I'll revisit the issue again to determine whether it is really a duplicate of #84 or not.

On my iOS/Android devices, I could not reproduce the flicker thouth it easily occurres on Web.

**Comment by therealjohnsummer** [comment] 2022-07-30 14:58
@espresso3389 Thats strange you couldnt reproduce - however, the screencast I sent was via my iOS simulator. The devices I can reproduce on are iOS: iPhone X, iphone SE (2nd Edition), iPad Air, iPad Pro, iPhone 11 Pro Max all Apples devices running iOS 15.5. My Android devices Samsung 10 Pro and Samsung 8 (Both Android 11). The rendering noise occurs mainly on swipe down with atleast 10 pages in the PDF and is more visible when you just swipe (without pinch) and make sure you do SLOW swipes down and then do an immediate up swipe or vice-versa.

**Comment by espresso3389** [comment] 2022-07-31 04:43
Wow, I can now reproduce the issue on my iPhone! I'm not sure why I could not reproduce it until today but anyway I did it and found that it's really identical (duplicate) to #84.

**Closed** 2022-07-31 04:44 UTC
