### ISSUE TITLE
 Build failed from android

### ISSUE THREAD

**Issue by warlesoncandido** [espresso3389/flutter_pdf_render#78] opened 2022-03-09 15:24 UTC
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/47983071/157472675-74a094e6-45dc-42a3-af3a-29b94f74b915.png">

**Comment by yashvcomply** [comment] 2022-06-21 06:51
I'm facing the same issue, any resolution so far? I checked everything is imported and works seamlessly on my other system.

**Comment by yashvcomply** [comment] 2022-06-25 10:12
Yeah correct, I am on mac and facing this. My other machine i.e. Windows, it works fine. 

Here's the issue from `verbose`

`[ +100 ms] [ +135 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[        ] [  +31 ms] debug_android_application: Complete
[ +500 ms] [ +465 ms] Persisting file store
[        ] [  +12 ms] Done persisting file store
[        ] [   +9 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 2,031ms.
[ +298 ms] [ +254 ms] ensureAnalyticsSent: 252ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :device_info_plus:preBuild UP-TO-DATE
[        ] > Task :device_info_plus:preDebugBuild UP-TO-DATE
[        ] > Task :device_info_plus:compileDebugAidl NO-SOURCE
[        ] > Task :file_picker:preBuild UP-TO-DATE
[        ] > Task :file_picker:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:preBuild UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugAidl NO-SOURCE
[        ] > Task :file_picker:compileDebugAidl NO-SOURCE
[   +3 ms] > Task :flutter_downloader:preBuild UP-TO-DATE
[        ] > Task :flutter_downloader:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_downloader:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_image_compress:preBuild UP-TO-DATE
[        ] > Task :flutter_image_compress:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_image_compress:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_ringtone_player:preBuild UP-TO-DATE
[        ] > Task :flutter_ringtone_player:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_ringtone_player:compileDebugAidl NO-SOURCE
[        ] > Task :image_picker_android:preBuild UP-TO-DATE
[        ] > Task :image_picker_android:preDebugBuild UP-TO-DATE
[        ] > Task :image_picker_android:compileDebugAidl NO-SOURCE
[        ] > Task :local_auth_android:preBuild UP-TO-DATE
[        ] > Task :local_auth_android:preDebugBuild UP-TO-DATE
[        ] > Task :local_auth_android:compileDebugAidl NO-SOURCE
[        ] > Task :onesignal_flutter:preBuild UP-TO-DATE
[        ] > Task :onesignal_flutter:preDebugBuild UP-TO-DATE
[        ] > Task :onesignal_flutter:compileDebugAidl NO-SOURCE
[        ] > Task :path_provider_android:preBuild UP-TO-DATE
[        ] > Task :path_provider_android:preDebugBuild UP-TO-DATE
[        ] > Task :path_provider_android:compileDebugAidl NO-SOURCE
[        ] > Task :permission_handler_android:preBuild UP-TO-DATE
[        ] > Task :permission_handler_android:preDebugBuild UP-TO-DATE
[        ] > Task :permission_handler_android:compileDebugAidl NO-SOURCE
[        ] > Task :shared_preferences_android:preBuild UP-TO-DATE
[        ] > Task :shared_preferences_android:preDebugBuild UP-TO-DATE
[        ] > Task :shared_preferences_android:compileDebugAidl NO-SOURCE
[        ] > Task :sqflite:preBuild UP-TO-DATE
[        ] > Task :sqflite:preDebugBuild UP-TO-DATE
[        ] > Task :sqflite:compileDebugAidl NO-SOURCE
[        ] > Task :url_launcher_android:preBuild UP-TO-DATE
[        ] > Task :url_launcher_android:preDebugBuild UP-TO-DATE
[        ] > Task :url_launcher_android:compileDebugAidl NO-SOURCE
[        ] > Task :webview_flutter_android:preBuild UP-TO-DATE
[        ] > Task :webview_flutter_android:preDebugBuild UP-TO-DATE
[        ] > Task :webview_flutter_android:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :device_info_plus:packageDebugRenderscript NO-SOURCE
[        ] > Task :file_picker:packageDebugRenderscript NO-SOURCE
[        ] > Task :flutter_downloader:packageDebugRenderscript NO-SOURCE
[        ] > Task :flutter_image_compress:packageDebugRenderscript NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:packageDebugRenderscript NO-SOURCE
[  +93 ms] > Task :flutter_ringtone_player:packageDebugRenderscript NO-SOURCE
[        ] > Task :image_picker_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :local_auth_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :onesignal_flutter:packageDebugRenderscript NO-SOURCE
[        ] > Task :path_provider_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :permission_handler_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :shared_preferences_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :sqflite:packageDebugRenderscript NO-SOURCE
[        ] > Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :webview_flutter_android:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :android_path_provider:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :device_info_plus:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :file_picker:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :flutter_downloader:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :flutter_image_compress:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :flutter_ringtone_player:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :image_picker_android:writeDebugAarMetadata UP-TO-DATE
[   +2 ms] > Task :local_auth_android:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :onesignal_flutter:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :path_provider_android:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :permission_handler_android:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :shared_preferences_android:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :sqflite:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :webview_flutter_android:writeDebugAarMetadata UP-TO-DATE
[  +95 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :device_info_plus:mergeDebugShaders UP-TO-DATE
[        ] > Task :device_info_plus:compileDebugShaders NO-SOURCE
[        ] > Task :device_info_plus:generateDebugAssets UP-TO-DATE
[        ] > Task :device_info_plus:packageDebugAssets UP-TO-DATE
[        ] > Task :file_picker:mergeDebugShaders UP-TO-DATE
[        ] > Task :file_picker:compileDebugShaders NO-SOURCE
[        ] > Task :file_picker:generateDebugAssets UP-TO-DATE
[        ] > Task :file_picker:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_downloader:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_downloader:compileDebugShaders NO-SOURCE
[        ] > Task :flutter_downloader:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_downloader:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_image_compress:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_image_compress:compileDebugShaders NO-SOURCE
[        ] > Task :flutter_image_compress:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_image_compress:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugShaders NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_ringtone_player:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :flutter_ringtone_player:compileDebugShaders NO-SOURCE
[        ] > Task :flutter_ringtone_player:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_ringtone_player:packageDebugAssets UP-TO-DATE
[        ] > Task :image_picker_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :image_picker_android:compileDebugShaders NO-SOURCE
[        ] > Task :image_picker_android:generateDebugAssets UP-TO-DATE
[        ] > Task :image_picker_android:packageDebugAssets UP-TO-DATE
[        ] > Task :local_auth_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :local_auth_android:compileDebugShaders NO-SOURCE
[        ] > Task :local_auth_android:generateDebugAssets UP-TO-DATE
[        ] > Task :local_auth_android:packageDebugAssets UP-TO-DATE
[        ] > Task :onesignal_flutter:mergeDebugShaders UP-TO-DATE
[        ] > Task :onesignal_flutter:compileDebugShaders NO-SOURCE
[        ] > Task :onesignal_flutter:generateDebugAssets UP-TO-DATE
[        ] > Task :onesignal_flutter:packageDebugAssets UP-TO-DATE
[        ] > Task :path_provider_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :path_provider_android:compileDebugShaders NO-SOURCE
[        ] > Task :path_provider_android:generateDebugAssets UP-TO-DATE
[        ] > Task :path_provider_android:packageDebugAssets UP-TO-DATE
[        ] > Task :permission_handler_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :permission_handler_android:compileDebugShaders NO-SOURCE
[        ] > Task :permission_handler_android:generateDebugAssets UP-TO-DATE
[        ] > Task :permission_handler_android:packageDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences_android:compileDebugShaders NO-SOURCE
[        ] > Task :shared_preferences_android:generateDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences_android:packageDebugAssets UP-TO-DATE
[        ] > Task :sqflite:mergeDebugShaders UP-TO-DATE
[        ] > Task :sqflite:compileDebugShaders NO-SOURCE
[        ] > Task :sqflite:generateDebugAssets UP-TO-DATE
[        ] > Task :sqflite:packageDebugAssets UP-TO-DATE
[        ] > Task :url_launcher_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :url_launcher_android:compileDebugShaders NO-SOURCE
[        ] > Task :url_launcher_android:generateDebugAssets UP-TO-DATE
[        ] > Task :url_launcher_android:packageDebugAssets UP-TO-DATE
[        ] > Task :webview_flutter_android:mergeDebugShaders UP-TO-DATE
[        ] > Task :webview_flutter_android:compileDebugShaders NO-SOURCE
[        ] > Task :webview_flutter_android:generateDebugAssets UP-TO-DATE
[        ] > Task :webview_flutter_android:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +492 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :device_info_plus:compileDebugRenderscript NO-SOURCE
[        ] > Task :device_info_plus:generateDebugResValues UP-TO-DATE
[        ] > Task :device_info_plus:generateDebugResources UP-TO-DATE
[        ] > Task :device_info_plus:packageDebugResources UP-TO-DATE
[        ] > Task :file_picker:compileDebugRenderscript NO-SOURCE
[        ] > Task :file_picker:generateDebugResValues UP-TO-DATE
[        ] > Task :file_picker:generateDebugResources UP-TO-DATE
[        ] > Task :file_picker:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_downloader:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_downloader:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_downloader:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_downloader:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_image_compress:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_image_compress:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_image_compress:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_image_compress:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_ringtone_player:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_ringtone_player:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_ringtone_player:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_ringtone_player:packageDebugResources UP-TO-DATE
[        ] > Task :image_picker_android:compileDebugRenderscript NO-SOURCE
[        ] > Task :image_picker_android:generateDebugResValues UP-TO-DATE
[        ] > Task :image_picker_android:generateDebugResources UP-TO-DATE
[        ] > Task :image_picker_android:packageDebugResources UP-TO-DATE
[        ] > Task :local_auth_android:compileDebugRenderscript NO-SOURCE
[        ] > Task :local_auth_android:generateDebugResValues UP-TO-DATE
[        ] > Task :local_auth_android:generateDebugResources UP-TO-DATE
[        ] > Task :local_auth_android:packageDebugResources UP-TO-DATE
[        ] > Task :onesignal_flutter:compileDebugRenderscript NO-SOURCE
[        ] > Task :onesignal_flutter:generateDebugResValues UP-TO-DATE
[        ] > Task :onesignal_flutter:generateDebugResources UP-TO-DATE
[        ] > Task :onesignal_flutter:packageDebugResources UP-TO-DATE
[        ] > Task :path_provider_android:compileDebugRenderscript NO-SOURCE
[        ] > Task :path_provider_android:generateDebugResValues UP-TO-DATE
[        ] > Task :path_provider_android:generateDebugResources UP-TO-DATE
[        ] > Task :path_provider_android:packageDebugResources UP-TO-DATE
[        ] > Task :permission_handler_android:compileDebugRenderscript NO-SOURCE
[        ] > Task :permission_handler_android:generateDebugResValues UP-TO-DATE
[        ] > Task :permission_handler_android:generateDebugResources UP-TO-DATE
[        ] > Task :permission_handler_android:packageDebugResources UP-TO-DATE
[        ] > Task :shared_preferences_android:compileDebugRenderscript NO-SOURCE
[        ] > Task :shared_preferences_android:generateDebugResValues UP-TO-DATE
[        ] > Task :shared_preferences_android:generateDebugResources UP-TO-DATE
[        ] > Task :shared_preferences_android:packageDebugResources UP-TO-DATE
[        ] > Task :sqflite:compileDebugRenderscript NO-SOURCE
[        ] > Task :sqflite:generateDebugResValues UP-TO-DATE
[        ] > Task :sqflite:generateDebugResources UP-TO-DATE
[        ] > Task :sqflite:packageDebugResources UP-TO-DATE
[        ] > Task :url_launcher_android:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :url_launcher_android:generateDebugResValues UP-TO-DATE
[        ] > Task :url_launcher_android:generateDebugResources UP-TO-DATE
[        ] > Task :url_launcher_android:packageDebugResources UP-TO-DATE
[        ] > Task :webview_flutter_android:compileDebugRenderscript NO-SOURCE
[        ] > Task :webview_flutter_android:generateDebugResValues UP-TO-DATE
[        ] > Task :webview_flutter_android:generateDebugResources UP-TO-DATE
[        ] > Task :webview_flutter_android:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :android_path_provider:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[  +96 ms] > Task :device_info_plus:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :device_info_plus:processDebugManifest UP-TO-DATE
[        ] > Task :file_picker:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :file_picker:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_downloader:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_downloader:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_image_compress:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_image_compress:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_ringtone_player:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_ringtone_player:processDebugManifest UP-TO-DATE
[        ] > Task :image_picker_android:extractDeepLinksDebug UP-TO-DATE
[   +2 ms] > Task :image_picker_android:processDebugManifest UP-TO-DATE
[        ] > Task :local_auth_android:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :local_auth_android:processDebugManifest UP-TO-DATE
[        ] > Task :onesignal_flutter:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :onesignal_flutter:processDebugManifest UP-TO-DATE
[        ] > Task :path_provider_android:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :path_provider_android:processDebugManifest UP-TO-DATE
[        ] > Task :permission_handler_android:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :permission_handler_android:processDebugManifest UP-TO-DATE
[        ] > Task :shared_preferences_android:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :shared_preferences_android:processDebugManifest UP-TO-DATE
[        ] > Task :sqflite:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :sqflite:processDebugManifest UP-TO-DATE
[        ] > Task :url_launcher_android:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :url_launcher_android:processDebugManifest UP-TO-DATE
[        ] > Task :webview_flutter_android:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :webview_flutter_android:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :device_info_plus:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :device_info_plus:parseDebugLocalResources UP-TO-DATE
[        ] > Task :device_info_plus:generateDebugRFile UP-TO-DATE
[        ] > Task :file_picker:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :file_picker:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugRFile UP-TO-DATE
[  +93 ms] > Task :file_picker:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_downloader:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_downloader:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_downloader:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_image_compress:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_image_compress:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_image_compress:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_ringtone_player:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_ringtone_player:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_ringtone_player:generateDebugRFile UP-TO-DATE
[        ] > Task :image_picker_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :image_picker_android:parseDebugLocalResources UP-TO-DATE
[        ] > Task :image_picker_android:generateDebugRFile UP-TO-DATE
[        ] > Task :local_auth_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :local_auth_android:parseDebugLocalResources UP-TO-DATE
[        ] > Task :local_auth_android:generateDebugRFile UP-TO-DATE
[        ] > Task :onesignal_flutter:compileDebugLibraryResources UP-TO-DATE
[  +99 ms] > Task :onesignal_flutter:parseDebugLocalResources UP-TO-DATE
[        ] > Task :onesignal_flutter:generateDebugRFile UP-TO-DATE
[        ] > Task :path_provider_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :path_provider_android:parseDebugLocalResources UP-TO-DATE
[        ] > Task :path_provider_android:generateDebugRFile UP-TO-DATE
[        ] > Task :permission_handler_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :permission_handler_android:parseDebugLocalResources UP-TO-DATE
[        ] > Task :permission_handler_android:generateDebugRFile UP-TO-DATE
[        ] > Task :shared_preferences_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :shared_preferences_android:parseDebugLocalResources UP-TO-DATE
[        ] > Task :shared_preferences_android:generateDebugRFile UP-TO-DATE
[        ] > Task :sqflite:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :sqflite:parseDebugLocalResources UP-TO-DATE
[        ] > Task :sqflite:generateDebugRFile UP-TO-DATE
[        ] > Task :url_launcher_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :url_launcher_android:parseDebugLocalResources UP-TO-DATE
[        ] > Task :url_launcher_android:generateDebugRFile UP-TO-DATE
[        ] > Task :webview_flutter_android:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :webview_flutter_android:parseDebugLocalResources UP-TO-DATE
[  +96 ms] > Task :webview_flutter_android:generateDebugRFile UP-TO-DATE
[  +96 ms] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :device_info_plus:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :device_info_plus:javaPreCompileDebug UP-TO-DATE
[        ] > Task :device_info_plus:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :device_info_plus:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :file_picker:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :file_picker:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :file_picker:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :file_picker:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :flutter_downloader:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_downloader:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_downloader:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_downloader:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :flutter_image_compress:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_image_compress:compileDebugKotlin UP-TO-DATE
[        ] > Task :flutter_image_compress:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_image_compress:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_image_compress:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :flutter_ringtone_player:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_ringtone_player:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_ringtone_player:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_ringtone_player:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :image_picker_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :image_picker_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :image_picker_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :image_picker_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :local_auth_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :local_auth_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :local_auth_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :local_auth_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :onesignal_flutter:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :onesignal_flutter:javaPreCompileDebug UP-TO-DATE
[ +101 ms] > Task :onesignal_flutter:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :onesignal_flutter:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :path_provider_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :path_provider_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :path_provider_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :path_provider_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :permission_handler_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :permission_handler_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :permission_handler_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :permission_handler_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :shared_preferences_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :shared_preferences_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :shared_preferences_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :sqflite:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :sqflite:javaPreCompileDebug UP-TO-DATE
[        ] > Task :sqflite:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :sqflite:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :url_launcher_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :url_launcher_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :url_launcher_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :url_launcher_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :webview_flutter_android:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :webview_flutter_android:javaPreCompileDebug UP-TO-DATE
[        ] > Task :webview_flutter_android:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :webview_flutter_android:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +293 ms] > Task :app:compileDebugJavaWithJavac FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 254 actionable tasks: 5 executed, 249 up-to-date
[        ] /Users/vproj/projs/MobileApp/proj_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:74: error: package
jp.espresso3389.pdf_render does not exist
[   +4 ms]       flutterEngine.getPlugins().add(new jp.espresso3389.pdf_render.PdfRenderPlugin());
[        ]                                                                    ^
[        ] 1 error
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 7s
[ +389 ms] Running Gradle task 'assembleDebug'... (completed in 7.9s)
[ +845 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 14,215ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +145 ms] ensureAnalyticsSent: 143ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1`

**Comment by espresso3389** [comment] 2022-06-25 13:21
There seems many similar issues reported on Flutter's issues:
https://github.com/flutter/flutter/issues?q=is%3Aissue+GeneratedPluginRegistrant.java+error%3A+package+does+not+exist+flutterEngine.getPlugins%28%29.add

But almost all of them us bit reproducable due to lack of info. and closed without any solution...

**Comment by yashvcomply** [comment] 2022-06-25 13:35
Ahh I see. Thanks for the info @espresso3389 much appreciated 🤝 👍

**Comment by DanielBerrioB** [comment] 2022-08-29 19:41
For those who are facing this issue this worked for me:

1) I've upgraded my gradle version to the latest one. So inside your build.gradle (android root folder) go to the dependencies section and change the gradle version to the latest one (For me I had to changed from 4.0.2 to 7.2.2, see image below)

![Screen Shot 2022-08-29 at 2 36 35 PM](https://user-images.githubusercontent.com/34080611/187283803-6db18bce-3b7f-429f-a130-17bf694456f0.png)

2) Also go to your gradle folder and open the gradle-wrapper.properties file and change the `distributionUrl` to the latest one, in my case it was the version `7.3.3`

![Screen Shot 2022-08-29 at 2 39 51 PM](https://user-images.githubusercontent.com/34080611/187284222-51b6679c-fb21-423e-b11a-e49841cf87a1.png)

It may take a while in the first run but then it worked fine for me.

**Closed** 2023-06-07 12:24 UTC
Labels: waiting_for_response
