### ISSUE TITLE
Getting issue while compiling app for macos desktop

### ISSUE THREAD

**Issue by ervinod** [espresso3389/flutter_pdf_render#96] opened 2022-10-14 10:42 UTC
Not able to run app for macos if using v 1.3.0
Please suggest any solution
(Note: I can not upgrade dependency to latest version due to compability of dart sdk with other plugins)

/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:1: error: expressions are not allowed at the top level
../../ios/Classes/SwiftPdfRenderPlugin.swift
^
/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:7: error: consecutive statements on a line must be separated by ';'
../../ios/Classes/SwiftPdfRenderPlugin.swift
      ^
      ;
/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:7: error: expressions are not allowed at the top level
../../ios/Classes/SwiftPdfRenderPlugin.swift
      ^
/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:1: error: cannot find operator '..' in scope; did you mean '...'?
../../ios/Classes/SwiftPdfRenderPlugin.swift
^~~~~~
...
/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:7: error: cannot find 'ios' in scope
../../ios/Classes/SwiftPdfRenderPlugin.swift
      ^~~
/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:11: error: cannot find 'Classes' in scope
../../ios/Classes/SwiftPdfRenderPlugin.swift
          ^~~~~~~
/Users/rentsher/.pub-cache/hosted/pub.dartlang.org/pdf_render-1.3.0/macos/Classes/SwiftPdfRenderPlugin.swift:1:19: error: cannot find 'SwiftPdfRenderPlugin' in scope
../../ios/Classes/SwiftPdfRenderPlugin.swift

**Comment by espresso3389** [comment] 2022-10-15 12:54
Please update your `pubspec.yaml` with the following lines that specify [the commit](https://github.com/espresso3389/flutter_pdf_render/tree/4fcfa554a73faa884b96025a209743a95677735d) corresponding to 1.3.0:

```yaml
dependencies:
  ...
  pdf_render:
    git:
      url: https://github.com/espresso3389/flutter_pdf_render
      ref: 4fcfa554a73faa884b96025a209743a95677735d
```

Because the issue is caused by the `pub.dev` uploaded codes and the original source code is not broken.

**Comment by espresso3389** [comment] 2022-10-15 12:56
Basically, it is a duplicate of #80.

**Closed by espresso3389** 2022-10-15 12:56 UTC
Labels: bug

**Comment by Aerofluxx** [comment] 2023-12-15 11:51
Hello,

reopening this issue for the newest version of pdf_render 1.4.5 building on MacOS.

```
/Users/myname/.pub-cache/hosted/pub.dev/pdf_render-1.4.5/macos/Classes/SwiftPdfRenderPlugin.swift:1:1: error: expressions are not allowed at the top level
../../ios/Classes/SwiftPdfRenderPlugin.swift
^
/Users/myname/.pub-cache/hosted/pub.dev/pdf_render-1.4.5/macos/Classes/SwiftPdfRenderPlugin.swift:1:7: error: consecutive statements on a line must be separated by ';'
../../ios/Classes/SwiftPdfRenderPlugin.swift
      ^
      ;
/Users/myname/.pub-cache/hosted/pub.dev/pdf_render-1.4.5/macos/Classes/SwiftPdfRenderPlugin.swift:1:7: error: expressions are not allowed at the top level
../../ios/Classes/SwiftPdfRenderPlugin.swift
      ^
/Users/myname/.pub-cache/hosted/pub.dev/pdf_render-1.4.5/macos/Classes/SwiftPdfRenderPlugin.swift:1:1: error: cannot find operator '..' in scope; did you mean '...'?
../../ios/Classes/SwiftPdfRenderPlugin.swift
^~~~~~
...
/Users/myname/.pub-cache/hosted/pub.dev/pdf_render-1.4.5/macos/Classes/SwiftPdfRenderPlugin.swift:1:7: error: cannot find 'ios' in scope
```

Thanks for taking a look into it.  👍

**Comment by tolotrasamuel** [comment] 2024-02-24 05:19
Thank you for point to pdfrx! Switching too
